spring.application.name=backend-api

# Configuración de Base de Datos inyectada por Variables de Entorno
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5434/banco_db}
spring.datasource.username=${DB_USER:devsu_user}
spring.datasource.password=${DB_PASSWORD:banco_password_2026}
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Puerto en el que levantará la aplicación Java
server.port=${APP_PORT:8080}

# Ocultar advertencias innecesarias de Hibernate en consola
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE